# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 74670dc5d9bbe09af31f250f3f58b8151b60d489f187a86699b5947ed8a585dc6eefb7afc860e30f317e5131e0be16525b7d8621c13d058db33f02e730c5e7d7

test:
  secret_key_base: 2cde028c3b508ee5ed14f0d87e55670396a84a5046e20704019304ecc6eaa52493bc70e79eb160201e0a467282c599049d4097cb87118ddac569435d3a0c5ae1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
